name: deploy to gh-pages

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          folder: build
