name: deploy to gh-pages

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]
  schedule:
    - cron: "*/10 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: check if release is ready for deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require('.github/workflows/scripts/checkForDeployment.js');
            await script({ github, context, TAG: "${{ github.event.workflow_run.head_branch }}" });

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

      - name: update issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require('.github/workflows/scripts/addDeploymentInfo.js');
            await script({ github, context, TAG: "${{ github.event.workflow_run.head_branch }}", run: "${{ github.run_id }}" });
