name: Node.js CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: install deps
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install node dependencies
        run: npm ci

      - name: run build
        run: npm run build --if-present

      - name: run unit
        run: npm run test

      - name: install playwright
        run: npx playwright install --with-deps

      - name: install browsers
        run: sudo apt-get install xvfb

      - name: run integration tests
        run: xvfb-run -a --server-args="-screen 0 1024x768x24" npm run e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
