name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: create release issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const title = ${{ github.ref }}

            const createIssue = async () => {
                await github.issues.create({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     title,
                     body: "test",
                });
            };

            createIssue();
