name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: create release issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const TAG = "${{ github.ref_name }}"

            const metaData = {
                owner: context.actor,
                repo: context.repo.repo,
            }

            const getIssue = async () => {
                const issues = await github.rest.issues.listForRepo({...metaData, labels: "RELEASE"})
                    .then((res) => res.data)
                    .catch((err) => null);

                for (const issue of issues) {
                    if (issue.title === TAG) {
                        return issue;
                    }
                }
            }

            const getRelease = async () => {
                const releases = await github.rest.repos.listReleases(metaData)
                    .then((res) => res.data)
                    .catch((err) => null);

                for (const release of releases) {
                    if (release.tag_name === TAG) {
                        return release;
                    }
                }
            }

            const issue = await getIssue();
            const release = await getRelease();

            const issueData = {
                ...metaData,
                title: TAG,
                labels: ['RELEASE'],
                issue_number: issue?.number ?? null,
                body: `author: ${metaData.owner}\n test\n`,
            };

            const releaseData = {
                ...metaData,
                tag_name: TAG,
                release_id: release?.id ?? null, 
                title: `Release ${TAG}`,
                body: `author: ${metaData.owner}\n test\n`,
            }

            if (issue) {
                github.rest.issues.update(issueData);
            } else {
                github.rest.issues.create(issueData);
            }

            if (release) {
                github.rest.repos.updateRelease(releaseData);
            } else {
                github.rest.repos.createRelease(releaseData);
            }
