name: Node.js CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install deps
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install node dependencies
        run: npm ci

      - name: run build
        run: npm run build --if-present

      - name: run unit tests for each commit
        run: |
          for commit in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
              echo "Running unit tests for " $commit
              git checkout $commit
              npm run test
          done

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: install xvfb
        run: sudo apt-get install xvfb

      - name: run integration
        run: |
          for commit in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
              echo "Running integration tests for " + $commit
              git checkout $commit
              xvfb-run -a --server-args="-screen 0 1024x768x24" npm run e2e
          done
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
